version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  

web:
        build: .
        command: rails s -p 3000 -b '0.0.0.0'
        volumes:
          - .:/app
        ports:
          - "3000:3000"
        depends_on:
          - db
        environment:
          DATABASE_HOST: db
          DATABASE_USERNAME: Galaxy
          DATABASE_PASSWORD: Galaxy
          DATABASE_NAME: Galaxy