services:
  backend:
    build: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api/produtos:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:galaxy@db:3306/dbase 
      
  web:
    build: ./client
    ports:
      - "4000:3000"
    volumes:
     - .client/produtos-react:/app
     - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm start


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: galaxy
      MYSQL_DATABASE: dbase
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

