# Usa uma imagem oficial do Ruby
FROM ruby:3.4.7

# Instala dependências do sistema
RUN apt-get update -qq && apt-get install -y \
  nodejs \
  default-mysql-client \
  build-essential \
  libpq-dev \
  libxml2-dev \
  libxslt1-dev \
  libffi-dev \
  && rm -rf /var/lib/apt/lists/*

# Define diretório de trabalho
WORKDIR /app

# Copia Gemfile e Gemfile.lock primeiro (para cache de bundler)
COPY produtos/Gemfile* ./

# Instala gems
RUN bundle install

# Copia todo o restante do projeto
COPY . .

# Expõe a porta padrão do Rails
EXPOSE 3000

# Comando padrão
CMD ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]